In [2]:
# Neural network imports
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D

In [3]:
# load the dataset
dataset = loadtxt('voice-emotion-database.csv', delimiter=',', skiprows=1)

In [4]:
# See dataset details
print(dataset[:3])
print(dataset.shape)

[[  0.          0.          0.          7.244975   -8.158391   -6.804606
   -5.95105    16.04601     4.259685    2.918404    3.899431   -8.787468
    2.029931   -9.035371   -1.614401   -9.214661    0.          5.
    1.          4.       ]
 [  1.          0.          0.          3.385026    9.644617   -3.468472
    6.205656   13.31692     4.477325   -3.002632  -21.12964    -4.892778
  -11.55352     6.817298    5.058506  -30.31255     0.          5.
    1.          4.       ]
 [  2.          0.          0.          5.719598    5.727946    6.571836
   19.76121    17.95665    12.09366    -0.2149866  -4.745448   -3.547788
   -9.468735   -1.699346   -1.552975  -29.19722     0.          5.
    1.          1.       ]]
(1066, 20)


In [5]:
# split into input (X) and output (y) variables
X = dataset[:,3:15] # Only the MFCC features
y = dataset[:,19] # Emotion label

# See X and y details
print(X[:3])
print(X.shape)

print(y[:3])
print(y.shape)

[[  7.244975   -8.158391   -6.804606   -5.95105    16.04601     4.259685
    2.918404    3.899431   -8.787468    2.029931   -9.035371   -1.614401 ]
 [  3.385026    9.644617   -3.468472    6.205656   13.31692     4.477325
   -3.002632  -21.12964    -4.892778  -11.55352     6.817298    5.058506 ]
 [  5.719598    5.727946    6.571836   19.76121    17.95665    12.09366
   -0.2149866  -4.745448   -3.547788   -9.468735   -1.699346   -1.552975 ]]
(1066, 12)
[4. 4. 1.]
(1066,)


In [6]:
from sklearn.model_selection import train_test_split # to split dataset into train and test

# Split the dataset in train and test
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3)

# input image dimensions
img_rows, img_cols = 3, 4

# Reshape inputs to 3D-matrices for the convolutional layers
X_train = X_train.reshape(X_train.shape[0],img_rows,img_cols,1).astype( 'float32' )
X_test = X_test.reshape(X_test.shape[0],img_rows,img_cols,1).astype( 'float32' )

# See Details
print("\nX_train:\n")
print(X_train[:3])
print(X_train.shape)

print("\nX_test:\n")
print(X_test[:3])
print(X_test.shape)

print("\ny_train:\n")
print(y_train[:3])
print(y_train.shape)

print("\ny_test:\n")
print(y_test[:3])
print(y_test.shape)


X_train:

[[[[  7.597784  ]
   [ -1.239229  ]
   [ -5.716656  ]
   [ -0.4919763 ]]

  [[  3.44356   ]
   [ -8.118807  ]
   [-10.71575   ]
   [  5.137786  ]]

  [[  9.765226  ]
   [ -0.897294  ]
   [ -4.969833  ]
   [  5.458729  ]]]


 [[[ -8.35018   ]
   [ -4.232736  ]
   [ -7.289896  ]
   [  7.297876  ]]

  [[  7.090691  ]
   [  4.183091  ]
   [ 22.40577   ]
   [  1.659072  ]]

  [[ -1.148264  ]
   [ -1.077869  ]
   [  0.5369895 ]
   [  3.897543  ]]]


 [[[ -2.121447  ]
   [ -3.403038  ]
   [-10.06158   ]
   [  0.03766751]]

  [[  1.512137  ]
   [  9.728447  ]
   [  5.861569  ]
   [  1.140742  ]]

  [[ -3.326549  ]
   [  0.2873299 ]
   [  3.116914  ]
   [ -1.941562  ]]]]
(746, 3, 4, 1)

X_test:

[[[[10.05547  ]
   [ 2.840231 ]
   [ 2.3077   ]
   [ 9.461814 ]]

  [[ 6.389001 ]
   [-9.577552 ]
   [-0.6508675]
   [-6.458837 ]]

  [[-5.338608 ]
   [-8.909947 ]
   [ 1.430915 ]
   [-0.8559995]]]


 [[[14.76785  ]
   [ 3.077632 ]
   [-1.814265 ]
   [-5.141767 ]]

  [[ 5.943084 ]
   [ 1.5615

In [7]:
from sklearn import preprocessing

# Binarize labels
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.fit_transform(y_test)

# See Details
print("\ny_train:\n")
print(y_train[:3])
print(y_train.shape)

print("\ny_test:\n")
print(y_test[:3])
print(y_test.shape)


y_train:

[[0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]
(746, 7)

y_test:

[[0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0]]
(320, 7)


In [52]:
# define input_shape
input_shape = (img_rows, img_cols, 1)

# define the keras model
model = Sequential()
model.add(Conv2D(30, kernel_size=(2, 2),activation='relu',input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(1, 1)))
model.add(Dropout(0.20))
model.add(Flatten())
model.add(Dense(15, activation= 'relu' ))
model.add(Dropout(0.2))
model.add(Dense(7, activation='softmax'))

In [53]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [54]:
# Define bath and epochs
batch_size = 64
epochs = 100

In [55]:
# Fit model
model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(X_test, y_test))

Train on 746 samples, validate on 320 samples
Epoch 1/100
746/746 [==============================] - 0s 630us/step - loss: 0.5811 - accuracy: 0.8231 - val_loss: 0.4595 - val_accuracy: 0.8531
Epoch 2/100
746/746 [==============================] - 0s 54us/step - loss: 0.4709 - accuracy: 0.8474 - val_loss: 0.4210 - val_accuracy: 0.8571
Epoch 3/100
746/746 [==============================] - 0s 58us/step - loss: 0.4274 - accuracy: 0.8560 - val_loss: 0.4116 - val_accuracy: 0.8571
Epoch 4/100
746/746 [==============================] - 0s 57us/step - loss: 0.4182 - accuracy: 0.8564 - val_loss: 0.4092 - val_accuracy: 0.8571
Epoch 5/100
746/746 [==============================] - 0s 63us/step - loss: 0.4131 - accuracy: 0.8571 - val_loss: 0.4087 - val_accuracy: 0.8571
Epoch 6/100
746/746 [==============================] - 0s 67us/step - loss: 0.4098 - accuracy: 0.8571 - val_loss: 0.4085 - val_accuracy: 0.8571
Epoch 7/100
746/746 [==============================] - 0s 62us/step - loss: 0.4099 - accu

746/746 [==============================] - 0s 69us/step - loss: 0.3841 - accuracy: 0.8600 - val_loss: 0.4139 - val_accuracy: 0.8540
Epoch 58/100
746/746 [==============================] - 0s 67us/step - loss: 0.3787 - accuracy: 0.8596 - val_loss: 0.4139 - val_accuracy: 0.8545
Epoch 59/100
746/746 [==============================] - 0s 95us/step - loss: 0.3750 - accuracy: 0.8596 - val_loss: 0.4142 - val_accuracy: 0.8554
Epoch 60/100
746/746 [==============================] - 0s 109us/step - loss: 0.3841 - accuracy: 0.8589 - val_loss: 0.4145 - val_accuracy: 0.8554
Epoch 61/100
746/746 [==============================] - 0s 95us/step - loss: 0.3818 - accuracy: 0.8571 - val_loss: 0.4139 - val_accuracy: 0.8554
Epoch 62/100
746/746 [==============================] - 0s 70us/step - loss: 0.3806 - accuracy: 0.8594 - val_loss: 0.4135 - val_accuracy: 0.8554
Epoch 63/100
746/746 [==============================] - 0s 50us/step - loss: 0.3798 - accuracy: 0.8583 - val_loss: 0.4143 - val_accuracy: 0.85

In [56]:
# Score Model
score = model.evaluate(X_test, y_test, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

320/320 [==============================] - 0s 65us/step
Test loss: 0.4148042440414429
Test accuracy: 0.8558036088943481


In [57]:
# Model Summary
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_12 (Conv2D)           (None, 2, 3, 30)          150       
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 2, 3, 30)          0         
_________________________________________________________________
dropout_23 (Dropout)         (None, 2, 3, 30)          0         
_________________________________________________________________
flatten_12 (Flatten)         (None, 180)               0         
_________________________________________________________________
dense_25 (Dense)             (None, 15)                2715      
_________________________________________________________________
dropout_24 (Dropout)         (None, 15)                0         
_________________________________________________________________
dense_26 (Dense)             (None, 7)               