In [2]:
# Neural network imports
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [10]:
# load the dataset
dataset = loadtxt('voice-emotion-database.csv', delimiter=',', skiprows=1)

In [16]:
# See dataset details
print(dataset[:3])
print(dataset.shape)

[[  0.          0.          0.          7.244975   -8.158391   -6.804606
   -5.95105    16.04601     4.259685    2.918404    3.899431   -8.787468
    2.029931   -9.035371   -1.614401   -9.214661    0.          5.
    1.          4.       ]
 [  1.          0.          0.          3.385026    9.644617   -3.468472
    6.205656   13.31692     4.477325   -3.002632  -21.12964    -4.892778
  -11.55352     6.817298    5.058506  -30.31255     0.          5.
    1.          4.       ]
 [  2.          0.          0.          5.719598    5.727946    6.571836
   19.76121    17.95665    12.09366    -0.2149866  -4.745448   -3.547788
   -9.468735   -1.699346   -1.552975  -29.19722     0.          5.
    1.          1.       ]]
(1066, 20)


In [21]:
# split into input (X) and output (y) variables
X = dataset[:,3:16] # Only the MFCC features
y = dataset[:,19] # Emotion label

# See X and y details
print(X[:3])
print(X.shape)

print(y[:3])
print(y.shape)

[[  7.244975   -8.158391   -6.804606   -5.95105    16.04601     4.259685
    2.918404    3.899431   -8.787468    2.029931   -9.035371   -1.614401
   -9.214661 ]
 [  3.385026    9.644617   -3.468472    6.205656   13.31692     4.477325
   -3.002632  -21.12964    -4.892778  -11.55352     6.817298    5.058506
  -30.31255  ]
 [  5.719598    5.727946    6.571836   19.76121    17.95665    12.09366
   -0.2149866  -4.745448   -3.547788   -9.468735   -1.699346   -1.552975
  -29.19722  ]]
(1066, 13)
[4. 4. 1.]
(1066,)


In [26]:
from sklearn.model_selection import train_test_split # to split dataset into train and test

# Split the dataset in train and test
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3)

# See Details
print("\nX_train:\n")
print(X_train[:3])
print(X_train.shape)

print("\nX_test:\n")
print(X_test[:3])
print(X_test.shape)

print("\ny_train:\n")
print(y_train[:3])
print(y_train.shape)

print("\ny_test:\n")
print(y_test[:3])
print(y_test.shape)


X_train:

[[  3.313348    4.443327   -4.241583   -4.363571   -3.05828     3.213391
    0.7997808 -13.07504    -5.934295   -8.439043   -5.750751    1.748661
  -18.85795  ]
 [ -2.45623    -1.182246   -1.553269    2.08759     6.993711    2.161998
    9.408565   12.53375    -1.515539   -2.081131    9.978843   14.14571
  -16.82007  ]
 [ -4.303337    9.984495   -4.385779    1.328745   10.73235     0.7617579
   23.07996     3.595927    8.985842   11.05848     8.256836   10.33507
   -9.41436  ]]
(746, 13)

X_test:

[[  8.043121     6.358935    -0.07838726 -12.6693     -12.74262
   12.06014     -8.499553    -3.254682    -3.674618   -11.83918
    3.313677     8.212853    -6.175133  ]
 [ 11.32908      4.75175      3.188044     5.696038    10.78317
   -6.493497   -14.68527     -8.222996    -5.558249     2.695052
   -4.184447    -2.294148   -27.21452   ]
 [ -0.8351212    5.359626     3.555175    10.59575      9.693429
    2.71118     12.54588      2.224721     1.877491    -6.727417
    4.83064    

In [29]:
from sklearn import preprocessing

# Binarize labels
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.fit_transform(y_test)

# See Details
print("\ny_train:\n")
print(y_train[:3])
print(y_train.shape)

print("\ny_test:\n")
print(y_test[:3])
print(y_test.shape)


y_train:

[[0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
(746, 7)

y_test:

[[0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]]
(320, 7)


In [38]:
# define the keras model
model = Sequential()
model.add(Dense(50, input_dim=13, activation='relu')) #input_dim = number of features. Hidden layer has 50, 20. Output layer has 7 (because of binarize)
model.add(Dense(20, activation='relu'))
model.add(Dense(7, activation='sigmoid'))

In [39]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
# Define bath and epochs
batch_size = 128
epochs = 12

In [41]:
# Fit model
model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(X_test, y_test))


Train on 746 samples, validate on 320 samples
Epoch 1/12
746/746 [==============================] - 0s 228us/step - loss: 2.1192 - accuracy: 0.3820 - val_loss: 1.7481 - val_accuracy: 0.4460
Epoch 2/12
746/746 [==============================] - 0s 25us/step - loss: 1.5552 - accuracy: 0.4678 - val_loss: 1.2975 - val_accuracy: 0.5268
Epoch 3/12
746/746 [==============================] - 0s 33us/step - loss: 1.1798 - accuracy: 0.5592 - val_loss: 1.0052 - val_accuracy: 0.6080
Epoch 4/12
746/746 [==============================] - 0s 42us/step - loss: 0.9354 - accuracy: 0.6310 - val_loss: 0.8137 - val_accuracy: 0.6737
Epoch 5/12
746/746 [==============================] - 0s 39us/step - loss: 0.7727 - accuracy: 0.6817 - val_loss: 0.6912 - val_accuracy: 0.7179
Epoch 6/12
746/746 [==============================] - 0s 34us/step - loss: 0.6677 - accuracy: 0.7204 - val_loss: 0.6176 - val_accuracy: 0.7554
Epoch 7/12
746/746 [==============================] - 0s 28us/step - loss: 0.6060 - accuracy: 

In [44]:
# Score Model
score = model.evaluate(X_test, y_test, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

320/320 [==============================] - 0s 19us/step
Test loss: 0.5021097153425217
Test accuracy: 0.8276785612106323


In [45]:
# Model Summary
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 50)                700       
_________________________________________________________________
dense_8 (Dense)              (None, 20)                1020      
_________________________________________________________________
dense_9 (Dense)              (None, 7)                 147       
Total params: 1,867
Trainable params: 1,867
Non-trainable params: 0
_________________________________________________________________
