In [3]:
# Neural network imports
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [5]:
# load the dataset
dataset = loadtxt('voice-emotion-database.csv', delimiter=',', skiprows=1)

In [6]:
# See dataset details
print(dataset[:3])
print(dataset.shape)

[[  0.          0.          0.          7.244975   -8.158391   -6.804606
   -5.95105    16.04601     4.259685    2.918404    3.899431   -8.787468
    2.029931   -9.035371   -1.614401   -9.214661    0.          5.
    1.          4.       ]
 [  1.          0.          0.          3.385026    9.644617   -3.468472
    6.205656   13.31692     4.477325   -3.002632  -21.12964    -4.892778
  -11.55352     6.817298    5.058506  -30.31255     0.          5.
    1.          4.       ]
 [  2.          0.          0.          5.719598    5.727946    6.571836
   19.76121    17.95665    12.09366    -0.2149866  -4.745448   -3.547788
   -9.468735   -1.699346   -1.552975  -29.19722     0.          5.
    1.          1.       ]]
(1066, 20)


In [7]:
# split into input (X) and output (y) variables
X = dataset[:,3:16] # Only the MFCC features
y = dataset[:,19] # Emotion label

# See X and y details
print(X[:3])
print(X.shape)

print(y[:3])
print(y.shape)

[[  7.244975   -8.158391   -6.804606   -5.95105    16.04601     4.259685
    2.918404    3.899431   -8.787468    2.029931   -9.035371   -1.614401
   -9.214661 ]
 [  3.385026    9.644617   -3.468472    6.205656   13.31692     4.477325
   -3.002632  -21.12964    -4.892778  -11.55352     6.817298    5.058506
  -30.31255  ]
 [  5.719598    5.727946    6.571836   19.76121    17.95665    12.09366
   -0.2149866  -4.745448   -3.547788   -9.468735   -1.699346   -1.552975
  -29.19722  ]]
(1066, 13)
[4. 4. 1.]
(1066,)


In [8]:
from sklearn.model_selection import train_test_split # to split dataset into train and test

# Split the dataset in train and test
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3)

# See Details
print("\nX_train:\n")
print(X_train[:3])
print(X_train.shape)

print("\nX_test:\n")
print(X_test[:3])
print(X_test.shape)

print("\ny_train:\n")
print(y_train[:3])
print(y_train.shape)

print("\ny_test:\n")
print(y_test[:3])
print(y_test.shape)


X_train:

[[ 10.86021    -0.1504712  -7.050648  -13.34398    -3.762597  -10.07538
   -4.320255    0.8074002   1.662185   -3.852825  -13.26163     3.004174
  -23.76107  ]
 [-20.17031     7.688166   -6.902145   15.45029     9.552048   -1.200928
   13.72213    -2.49684    11.76603    -6.941161    1.724953    6.110147
  -21.93117  ]
 [ -2.741963   -5.573832    1.295266    6.534232    8.063975    7.205008
   10.84907     2.744319    2.135926   -0.7263327   7.643946    3.96128
  -10.77666  ]]
(746, 13)

X_test:

[[ 6.632766e+00  6.211563e+00  6.034946e+00  3.301121e+01 -2.390878e+00
   8.948273e+00 -7.841763e+00 -7.805614e+00 -3.095579e+00  4.398633e+00
  -1.238064e+00 -1.834961e+01 -4.059555e+00]
 [-2.587318e-01 -5.702300e+00  7.713166e+00  1.141300e+01  6.923450e+00
   9.285526e+00  1.123824e+01  1.753032e+00  8.851054e+00  2.128385e+00
   2.319431e-02 -2.441559e+00 -1.552758e+01]
 [ 1.152659e+00  2.549862e+00 -4.846608e+00  2.665312e+00 -1.144581e-01
   2.994903e+00  1.578110e+00  3.4190

In [9]:
from sklearn import preprocessing

# Binarize labels
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.fit_transform(y_test)

# See Details
print("\ny_train:\n")
print(y_train[:3])
print(y_train.shape)

print("\ny_test:\n")
print(y_test[:3])
print(y_test.shape)


y_train:

[[0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1]]
(746, 7)

y_test:

[[1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]]
(320, 7)


In [53]:
# define the keras model
model = Sequential()
model.add(Dense(30, input_dim=13, activation='relu')) #input_dim = number of features. Hidden layer has 50, 20. Output layer has 7 (because of binarize)
model.add(Dense(15, activation='relu'))
model.add(Dense(7, activation='sigmoid'))

In [54]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [55]:
# Define bath and epochs
batch_size = 64
epochs = 100

In [56]:
# Fit model
model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(X_test, y_test))

Train on 746 samples, validate on 320 samples
Epoch 1/100
746/746 [==============================] - 0s 377us/step - loss: 1.1036 - accuracy: 0.6771 - val_loss: 0.9278 - val_accuracy: 0.6871
Epoch 2/100
746/746 [==============================] - 0s 60us/step - loss: 0.8592 - accuracy: 0.7129 - val_loss: 0.7486 - val_accuracy: 0.7286
Epoch 3/100
746/746 [==============================] - 0s 48us/step - loss: 0.7288 - accuracy: 0.7384 - val_loss: 0.6564 - val_accuracy: 0.7487
Epoch 4/100
746/746 [==============================] - 0s 61us/step - loss: 0.6525 - accuracy: 0.7556 - val_loss: 0.6051 - val_accuracy: 0.7692
Epoch 5/100
746/746 [==============================] - 0s 63us/step - loss: 0.6046 - accuracy: 0.7717 - val_loss: 0.5686 - val_accuracy: 0.7777
Epoch 6/100
746/746 [==============================] - 0s 61us/step - loss: 0.5674 - accuracy: 0.7832 - val_loss: 0.5415 - val_accuracy: 0.7866
Epoch 7/100
746/746 [==============================] - 0s 67us/step - loss: 0.5402 - accu

746/746 [==============================] - 0s 48us/step - loss: 0.3759 - accuracy: 0.8577 - val_loss: 0.4296 - val_accuracy: 0.8509
Epoch 58/100
746/746 [==============================] - 0s 45us/step - loss: 0.3748 - accuracy: 0.8577 - val_loss: 0.4297 - val_accuracy: 0.8509
Epoch 59/100
746/746 [==============================] - 0s 55us/step - loss: 0.3739 - accuracy: 0.8585 - val_loss: 0.4297 - val_accuracy: 0.8513
Epoch 60/100
746/746 [==============================] - 0s 49us/step - loss: 0.3735 - accuracy: 0.8577 - val_loss: 0.4297 - val_accuracy: 0.8513
Epoch 61/100
746/746 [==============================] - 0s 36us/step - loss: 0.3727 - accuracy: 0.8583 - val_loss: 0.4298 - val_accuracy: 0.8518
Epoch 62/100
746/746 [==============================] - 0s 53us/step - loss: 0.3717 - accuracy: 0.8577 - val_loss: 0.4298 - val_accuracy: 0.8513
Epoch 63/100
746/746 [==============================] - 0s 41us/step - loss: 0.3708 - accuracy: 0.8581 - val_loss: 0.4295 - val_accuracy: 0.850

In [57]:
# Score Model
score = model.evaluate(X_test, y_test, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

320/320 [==============================] - 0s 44us/step
Test loss: 0.4343851327896118
Test accuracy: 0.8491071462631226


In [58]:
# Model Summary
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_36 (Dense)             (None, 30)                420       
_________________________________________________________________
dense_37 (Dense)             (None, 15)                465       
_________________________________________________________________
dense_38 (Dense)             (None, 7)                 112       
Total params: 997
Trainable params: 997
Non-trainable params: 0
_________________________________________________________________
